- name: Ensure repository key for Prosody is in place
  apt_key: url=https://prosody.im/files/prosody-debian-packages.key state=present
  tags:
    - dependencies

- name: Add Prosody repository
  apt_repository: repo="deb http://packages.prosody.im/debian {{ ansible_distribution_release }} main"
  tags:
    - dependencies

- name: Install Prosody and dependencies from official repository
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - prosody
    - lua-sec
  tags:
    - dependencies

- name: Create Prosody data directory
  file: state=directory path=/decrypted/prosody owner=prosody group=prosody

- name: Configure Prosody
  template: src=prosody.cfg.lua.j2 dest=/etc/prosody/prosody.cfg.lua group=root owner=root
  notify: restart prosody

- name: Copy SSL private key and cert
  shell: cp /etc/letsencrypt/live/{{ domain }}/{{ item }} /etc/prosody/certs
  with_items:
    - privkey.pem
    - cert.pem

- name: Assert mode and ownership on SSL private key and cert
  file: dest=/etc/prosody/certs/{{ item }} owner=root group=prosody mode=0640
  with_items:
    - privkey.pem
    - cert.pem

- name: Update certificate renewal cron job
  lineinfile: dest=/etc/cron.monthly/letsencrypt-renew state=present
    line="cp /etc/letsencrypt/live/{{ domain }}/{privkey,cert}.pem /etc/prosody/certs; chown root.prosody /etc/prosody/certs/{privkey,cert}.pem; chmod 640 /etc/prosody/certs/{privkey,cert}.pem; service prosody restart"
    insertafter="EOF"

- name: Create Prosody accounts
  command: prosodyctl register {{ item.name }} {{ prosody_virtual_domain }} "{{ item.password }}"
  with_items: prosody_accounts

- name: Set firewall rules for Prosody
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - 5222  # xmpp c2s
    - 5269  # xmpp s2s
  tags: ufw
