- name: Download check-rbl
  get_url: url=https://raw.githubusercontent.com/lukecyca/check-rbl/920f503f05e0aad785f01cb9ab356e239fee4924/check-rbl.pl dest=/opt/check-rbl.pl sha256sum=1f2a805fe8ba4d9918fafdef2c4d116bb2a92701c9fb790a85b73ffd5a4f4800
- name: Install nightly check-rbl cronjob
  cron: name="check-rbl" hour="2" minute="0" job="perl /opt/check-rbl.pl -i {{ ansible_default_ipv4.address }}"
