- name: Install Solr and related packages
  apt: pkg={{ item }} state=installed
  with_items:
    - dovecot-solr
    - solr-tomcat
  tags:
    - dependencies

- name: Work around Debian bug and copy Solr schema file into place
  copy: src=solr-schema.xml dest=/etc/solr/conf/schema.xml group=root owner=root

- name: Copy tweaked Tomcat config file into place
  copy: src=etc_{{ tomcat_package_name }}_server.xml dest=/etc/{{ tomcat_package_name }}/server.xml group={{ tomcat_package_name }} owner=root
  notify: restart solr

- name: Copy tweaked Solr config file into place
  copy: src=etc_solr_conf_solrconfig.xml dest=/etc/solr/conf/solrconfig.xml group=root owner=root
  notify: restart solr

- name: Create Solr index directory
  file: state=directory path=/decrypted/solr group={{ tomcat_package_name }} owner={{ tomcat_package_name }}
  notify: restart solr
