- name: Install Solr and related packages on wheezy from backports
  apt: pkg={{ item }} state=installed default_release=wheezy-backports
  with_items:
    - dovecot-solr
    - solr-tomcat
  when: ansible_distribution_release == 'wheezy'
  tags:
    - dependencies

- name: Install Solr and related packages on distributions other than wheezy
  apt: pkg={{ item }} state=installed
  with_items:
    - dovecot-solr
    - solr-tomcat
  when: ansible_distribution_release != 'wheezy'
  tags:
    - dependencies

- name: Work around Debian bug and copy Solr schema file into place
  copy: src=solr-schema.xml dest=/etc/solr/conf/schema.xml group=root owner=root

- name: Copy tweaked Tomcat config file into place
  copy: src=etc_tomcat6_server.xml dest=/etc/tomcat6/server.xml group=tomcat6 owner=root
  notify: restart solr

- name: Copy tweaked Solr config file into place
  copy: src=etc_solr_conf_solrconfig.xml dest=/etc/solr/conf/solrconfig.xml group=root owner=root
  notify: restart solr

- name: Create Solr index directory
  file: state=directory path=/decrypted/solr group=tomcat6 owner=tomcat6
  notify: restart solr
