common_timezone: 'Etc/UTC'
admin_email: "{{ main_user_name }}@{{ domain }}"
main_user_shell: "/bin/bash"
friendly_networks:
  - ""

# encfs
secret_root: '{{ inventory_dir | realpath }}'
secret_name: 'secret'
secret: '{{ secret_root + "/" + secret_name }}'
encfs_password: "{{ lookup('password', secret + '/' + 'encfs_password', length=32) }}"


# let's encrypt
letsencrypt_server: "https://acme-v02.api.letsencrypt.org/directory"

# ssh
# Following https://infosec.mozilla.org/guidelines/openssh
kex_algorithms: "curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256"
ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
macs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"

# ntp
ntp_servers:
  # use nearby ntp servers by default
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org
  # use servers tailored to the server location
  # See http://www.pool.ntp.org/en/use.html
  # - 0.north-america.pool.ntp.org
  # - 1.north-america.pool.ntp.org
  # - 2.north-america.pool.ntp.org
  # - 3.north-america.pool.ntp.org
