- name: Install logwatch
  apt: pkg={{ item }} state=installed
  with_items:
    - libdate-manip-perl
    - logwatch
  tags:
    - dependencies

- name: Configure logwatch
  template: src=etc_logwatch_conf_logwatch.conf.j2 dest=/etc/logwatch/conf/logwatch.conf

- name: Remove logwatch's dist cronjob
  file: state=absent path=/etc/cron.daily/00logwatch

- name: Configure weekly logwatch cronjob
  cron: special_time=weekly job=/usr/sbin/logwatch name=logwatch
