
- name: Install cgit dependencies
  apt: pkg={{ item }} state=installed
  with_items:
    - groff
    - libssl-dev
    - python-pip

- name: Install cgit pip dependencies
  pip: name={{ item }}
  with_items:
    - docutils
    - pygments

- name: Download cgit release
  get_url: url=http://git.zx2c4.com/cgit/snapshot/cgit-{{ cgit_version }}.tar.xz
           dest=/root/cgit-{{ cgit_version }}.tar.xz

- name: Decompress cgit source
  command: tar xvfJ /root/cgit-{{ cgit_version }}.tar.xz
           chdir=/root
           creates=/root/cgit-{{ cgit_version }}/configure

- name: Build and install cgit
  shell: make get-git ; make ; make install
         executable=/bin/bash
         chdir=/root/cgit-{{ cgit_version }}
         creates=/var/www/htdocs/cgit/cgit.cgi

- name: Copy cgitrc
  template: src=etc_cgitrc.j2 dest=/etc/cgitrc
            group=www-data
            owner=www-data

- name: Rename existing Apache cgit virtualhost
  command: mv /etc/apache2/sites-available/cgit /etc/apache2/sites-available/cgit.conf removes=/etc/apache2/sites-available/cgit

- name: Remove old sites-enabled/cgit symlink (new one will be created by a2ensite)
  command: rm /etc/apache2/sites-enabled/cgit removes=/etc/apache2/sites-enabled/cgit

- name: Configure the Apache HTTP server for cgit
  template: src=etc_apache2_sites-available_cgit.j2
            dest=/etc/apache2/sites-available/cgit.conf
            group=root
            owner=root

- name: Enable Apache cgi module
  command: a2enmod cgi creates=/etc/apache2/mods-enabled/cgi.load
  notify: restart apache

- name: Enable Apache rewrite module
  command: a2enmod rewrite creates=/etc/apache2/mods-enabled/rewrite.load
  notify: restart apache

- name:  Enable cgit site
  command: a2ensite cgit.conf creates=/etc/apache2/sites-enabled/cgit.conf
  notify: restart apache
