---
# Installs and configures ferm, which in turn uses iptables for firewall management

- name: Install ferm
  apt: pkg=ferm state=present

- name: Create ferm configuration directory
  file: path=/etc/ferm state=directory

- name: Copy ferm firewall rules into place
  copy: src=etc_ferm_ferm.conf dest=/etc/ferm/ferm.conf
  notify:
    - reload ferm rules
