- name: restart postfix
  service: name=postfix state=restarted

- name: restart dovecot
  service: name=dovecot state=restarted

- name: restart opendkim
  service: name=opendkim state=restarted

- name: restart solr
  service: name=tomcat6 state=restarted

- name: import sql postfix
  action: shell PGPASSWORD='{{ mail_db_password }}' psql -h localhost -d {{ mail_db_database }} -U {{ mail_db_username }} -f /etc/postfix/import.sql --set ON_ERROR_STOP=1
  notify: restart postfix

- name: restart opendmarc
  service: name=opendmarc state=restarted
